version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for package.json and package-lock.json files in the root directory
    directory: '/'
    # Check for updates daily
    schedule:
      interval: 'daily'
    # Specify labels for pull requests
    labels:
      - 'dependencies'
      - 'automated'
    # Allow up to 10 open pull requests at a time
    open-pull-requests-limit: 10
    # Create pull requests for version updates
    pull-request-branch-name:
      # Use a prefix for the branch name
      separator: '-'
    # Assign reviewers
    reviewers:
      - '$OWNER'
    # Group all updates together
    groups:
      dev-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    # Set version strategy
    versioning-strategy: auto
    # Ignore certain dependencies
    # ignore:
    #  - dependency-name: "express"
    #    versions: ["4.x", "5.x"]
